services:
  web:
    build:
      context: ./bin/${PHPVERSION}
    container_name: "${COMPOSE_PROJECT_NAME}-${PHPVERSION}"
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    links:
      - db

  db:
    build:
      context: "./bin/${DATABASE}"
    container_name: "${COMPOSE_PROJECT_NAME}-${DATABASE}"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diablo
      MYSQL_USER: diablo
      MYSQL_PASSWORD: diablo
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  admin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: diablo
      PMA_PASSWORD: diablo
    links:
      - db
